training:
  epochs: 200
  batch_size: 2
  num_workers: 8
  early_stop_patience: 30
  save_max: 5
  interval: 1
  tb: true
  data_split: false
  local: False
  train_length: 500
  val_length: 100
  test_length: 10

model:
  name: "aa_unet"
  in_channel: 4
  mid_channel: 32
  out_channel: 4
  fusion_flag: true
  total_parms: null

optimizer:
  type: "adamw"
  lr: 0.0002
  wd: 0.00001
  reduce_patience: 3
  reduce_factor: 0.9

scheduler:
  type: "cosine"
  cosine_T_0: 10
  cosine_T_mult: 2
  cosine_eta_min: 1e-6
  cosine_T_max: 200

loss:
  type: "diceloss"

paths:
  resume: false
  root: "/root/workspace/BraTS_Solution"
  data_root: "/root/workspace/BraTS_Solution/data"
  output: "/root/workspace/BraTS_Solution/output"
  train_csv: "/root/workspace/BraTS_Solution/data/raw/brats21_original/train.csv"
  val_csv: "/root/workspace/BraTS_Solution/data/raw/brats21_original/val.csv"
  test_csv: "/root/workspace/BraTS_Solution/data/raw/brats21_original/test.csv"
  results_root: "/root/workspace/BraTS_Solution/results"

commit: "debug"